import Navbar from "@/components/Navbar";
import Welcome from "@/components/Welcome";
import "./globals.css";


export const metadata = {
  title: "APHSAGH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
       
      </body>
    </html>
  );
}
